### PR TITLE
Make Python code compliant with PEP8 and PEP257

### PR DESCRIPTION
**Pull request by allanlewis**
The Python code is currently not compliant with common standards like [PEP8](https://www.python.org/dev/peps/pep-0008/) (code style) and [PEP 257](https://www.python.org/dev/peps/pep-0257/) (docstring conventions). This pull request makes various non-functional changes to the code to rectify the situation.

### CODE REVIEW

**Comment by allanlewis** [comment]
I've updated this to correct Python 3.x code as well as Python 2.x.

**Comment by allanlewis** [comment]
@jongurock why have you closed this?

**Comment by jonrgurock** [comment]
Hi @allanlewis,

The API bindings have recently changed and I am cleaning up old pull requests which had not been monitored for some time.

**Comment by allanlewis** [comment]
I've just rebased this on master - it looks like you've integrated several of my commits anyway 😈 
I'll raise a new PR with the remaining commits.

**Pull request closed without merging**
